### ISSUE TITLE
Need to be able to munge JSON files

### ISSUE THREAD

**Issue by clangen2** [ElectionDataAnalysis/election_data_analysis#113]
Many states give us nice TSVs or CSVs, but sometimes (Delaware) we can also get JSON.

**Comment by sfsinger19103** [comment]
What munging parameters are necessary to use pandas [read_json ](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html) function to pull data directly from the file into a pandas dataframe that has informative column names? @clangen2 it would be helpful if you figured this out!

**Comment by wstlabs** [comment]
Where are you seeing JSON files posted?  For 2018g for example, they seem to be using a custom "semicolon-separated" (presumably CSV-equivalent):

https://elections.delaware.gov/archive/elect18/elect18_general/data/stwres.txt

However I only poked around for a few seconds - if you can point to where exactly the JSON files reside, that'd be very helpful.

**Comment by clangen2** [comment]
The 2020 data is put in the archive differently, and just has a link to another site: https://elections.delaware.gov/results/html/index.shtml?electionId=PP2020#electionReport3. The only csv available for download is the statewide results, but they populate the tables with JSON that, with the chrome developer tools, I was able to see comes from this url: https://elections.delaware.gov/results/prod/json/Election_ByElectionDistrict_ID_PP2020.json?_=1600463854270.

**Comment by wstlabs** [comment]
@clangen2 - thanks for the quick follow-up.  So for recent results we'll have to go by the JSON files, then.

Fortunately, when we look at these files they turn out to have a "flat" (list-of-dict) structure that (as @sfsinger19103 suggested) loads easily into pandas:

`
>>> import pandas as pd
>>> df = pd.read_json("Election_ByElectionDistrict_ID_PP2020.json")
>>> df.keys()
Index(['Election Id', 'Election Name', 'Results Type', 'Election District',
       'Party Name', 'Contest Sorting Order', 'Contest Title',
       'Candidate Name', 'Pos', 'Machine Votes', 'Absentee Votes',
       'Total Votes', 'Percentage'],
      dtype='object')
`

Though this structure is very simple, best I can tell there are no config files parameters that currently support it (i.e. either JSON files of any kind, or this particular internal structure).   

From that there are basically two paths we can take:

(1) Adjust the file slurping code (probably the `read_single_file` function) so that, when given `file_type="json"` it assumes that the JSON file represents just such a "flat" (list-of-dict) structure as described above, and attempts to perform a Pandas import on it, as above.

(2) Allow for some kind of one-off preprocessing step (whereby an extra small script needs to be written) that "pivots" the data from JSON to CSV.

It does seem that option (1) is greatly preferable in this case (and the coding change will be about as easy to write as it was to describe, as above).

Only caveat is that we'll need to adjust the documentation as well (ideally in the same PR) so that people have some way of know that, when they select `filetype="json"` that it means not just any JSON file, but "a JSON file with a table-like structure (such that it can be read directly into a Pandas DataFrame)."  It won't be bullet-proof -- it definitely won't be guaranteed to work for any results file that may come at us, on some other website -- but it will at least give people a ballpark idea of what kind of structure is expected (and why it may not work on use cases besides this one).

**Comment by sfsinger19103** [comment]
Anybody know how to decode the number in the url?

> https://elections.delaware.gov/results/prod/json/Election_ByElectionDistrict_ID_PP2020.json?**_=1600463854270.**

If we had to we could just run through lots of numbers and download any files we find, but it would be quicker -- and less likely to trigger alarms -- if we could cut down the universe of numbers.

**Comment by wstlabs** [comment]
Yeah, I was able to pull the file both with and without the magical integer value (presumably a timestamp for cache-busting purposes) just now - and both versions are identical.
