### ISSUE TITLE
Allow munger to omit BallotMeasureContest and BallotMeasureSelection

### ISSUE THREAD

**Issue by sfsinger19103** [ElectionDataAnalysis/election_data_analysis#147]

**Comment by wstlabs** [comment]
This was one of the many small (but incremental) issues slowing down my attempt to get the WI data on its feet.

In general, if a certain directive isn't need to load a given use case - then it shouldn't be required (and if presented in the config file, ideally a warning should issued).

So -- since the end result is confusion on the part of the user (and more importantly: time lost in getting the model up and running) -- I'd say this counts as a bug.

**Comment by sfsinger19103** [comment]
This change may have unintended consequences. Fix may take some time, and testing will be essential.
