### ISSUE TITLE
Improve organization of munger code

### ISSUE THREAD

**Issue by sfsinger19103** [ElectionDataAnalysis/election_data_analysis#149]
file_types were developed ad hoc, starting with flat files. The different file types could be distinguished more systematically by answers to the following questions:

- what pandas function is needed to read contents from the results file?
- How can we separate the contents into basic blocks of data?
- How do we read data from any one basic block?
- What desired information do we want to read from the material outside the basic blocks of data?

**Comment by wstlabs** [comment]
One thing I've noticed is that sometimes a `file_type` is introduced that sounds generic (e.g. `xls-multi`) but is in fact effectively specific to a single use case.

So - in recognition of the fact that it's most likely a one-off - it would be better to use a one-off `file_type` - e.g. `xls-multi-WI`.  Otherwise people will think it will work on generic multi-book XLS files, when most likely it won't.

**Comment by sfsinger19103** [comment]
Done in `feature-new-munger` PR
