### ISSUE TITLE
Combine "Presidential Preference" and "Primary" contests into one category "Primary" for output to the front end

### ISSUE THREAD

**Issue by sfsinger19103** [ElectionDataAnalysis/election_data_analysis#170]
**On the front end only** users should see the list of elections as "2020 General, 2020 Primary, 2018 General, 2016 General". Any user choosing "2020 Primary" should have further options (e.g., contests, candidates) restricted to the union of options from all 2020 non-general elections.

**Comment by ericmtsai** [comment]
My question here is whether this should be a code thing or a data storage thing. If we never have a use for splitting out a single year's primary into presidential vs non-presidential (which I assume makes up the entirety of the non-general elections), then shouldn't we just change the labels for 2020 Presidential Primary and 2020 Non-Presidential Primary to both use 2020 Primary?

I assume since you started with "On the front end only" that there is reasoning for this, but want to double check bc of the slack conversation where we all seemed to agree to that combining was a good idea.

**Comment by sfsinger19103** [comment]
My "front end" thinking was purely defensive, to avoid unintended consequences. Could be talked out of it.

I guess we could think of this as simply a case of multiple data files for a single "election" -- in which case the clean way to proceed might be to change all those .ini files to `election=2020 Primary`.  It's a disruption for the data collectors, but maybe that's the least risky way to proceed.

**Comment by ericmtsai** [comment]
I think that's not only the least risky way, but also the correct way to proceed - store it in the DB the way we want it, absent a good reason to do otherwise. Certainly, potential disruption at this date may be a good enough reason _not_ to do it that way, although that would need to be balanced with figuring out to manifest it with a UNION through the API.

But if it's a matter of saying to the data collectors, "Do it this way now" then I think that's the way to move forward.

**Comment by ericmtsai** [comment]
We decided this is a backend issue.

**Comment by sfsinger19103** [comment]
Todo list:

- backwards: change all existing .ini files in g-drive and other places to 2020 Primary for both 2020 Primary and 2020PPP
- backwards: remove 2020 Presidential Preference Primary from all Election.txt files (including template)
- forwards: tell data collectors to do same
- Document in UserGuide.md
