### ISSUE TITLE
Parent-child weirdness in `ComposingReportingUnitJoin` table 

### ISSUE THREAD

**Issue by wstlabs** [ElectionDataAnalysis/election_data_analysis#42]
After running the PA-2018g model we end up with an instance of the `ComposingReportingUnitJoin` where almost every child unit has two parents: one Id for the statewide entity (like one would expect), and another pointing back to itself:

```
select * from "ComposingReportingUnitJoin" order by "ChildReportingUnit_Id", "ParentReportingUnit_Id" limit 6;
 Id  | ParentReportingUnit_Id | ChildReportingUnit_Id 
-----+------------------------+-----------------------
 742 |                     62 |                    62
 402 |                    129 |                    62
 743 |                     63 |                    63
 403 |                    129 |                    63
 744 |                     64 |                    64
 404 |                    129 |                    64
```

Seems unlikely that this the intended design.

**Comment by sfsinger19103** [comment]
Worst case, this adds load to the db. It may save time in pulling data, since we aggregate data from all sub-reporting units, and sometimes this includes the reporting unit itself. For example, a state might have a results file by precinct for election-day results, along with a results file by county for absentee results. Pulling results by county, we want to include both the precinct-level and the county-level results. As is, this means pulling results from all "children".  It could be worse: https://www.youtube.com/watch?v=rXU-ZdmzNmo
