### ISSUE TITLE
An incremental release process (ideally with semantic versioning) would be very helpful

### ISSUE THREAD

**Issue by wstlabs** [ElectionDataAnalysis/election_data_analysis#52]
Per a chat w/ @Raghu-Srungavarapu this afternoon:

Even in a project of this scale it would be very helpful to some kind of process for incremental (internal) releases in place.  That is, some way of 'checkpointing' our code so we can say "OK, here's a stable version you can pull and do further testing / development on. BTW it includes pull requests X, Y, Z".

I see now we're using git tags [1] which is nice - but tags are meaningless if code (and functionality) keeps changing but the tag value always stays the same (ours currently says `v1.0.0` even as new PRs keep coming in).  Better would be to start with a much more modest release number (e.g. `v0.1.1`) and increment that *slowly* (e.g. `v0.1.2`, `v0.1.3`) as new releases are announced.[2]. 

BTW as "release" doesn't have to be anything more magical than a sequence of PR merges (such that the end result is deemed "stable" by one criterion or another).  But the point is, at this point it would be desirable to have *some* form of (properly versioned) incremental releases - so we at least of some way of saying "ok, I tried doing <this> on `v0.1.3` and here's what happened" in our issue writeups.

Also, it'd be nice to have a changelog[3] with every release (which can just be a file `CHANGES.md` at the top of the repo).  And of course the `version` parameter in the `setup.py` should always be in synch with the current `git tag` (there are ways of getting these to synch automatically; but for now, manual fudging will do just fine).

Right now the only way to tell if anything has changed in the state of the code is to look at the output of `git log` and `git branch` and then *surmise* from that that something has been fixed or not (which can sort of work, but not very well).  

Finally, it'd be nice to see some kind of branching model apart from "everything into `main`" (which is of course equivalent to "everything into `master`).  For example a bi-level (`master` / `develop`) or 3-level (`master` / `qa` / `develop`) model would make it easier to identify stable releases for testing and production.  There are lots of fine articles and blog posts on this topic e.g. [4], [5].

[1] https://git-scm.com/book/en/v2/Git-Basics-Tagging

[2] https://semver.org

[3] https://keepachangelog.com/en/1.0.0/

[4] https://nvie.com/posts/a-successful-git-branching-model/

[5] https://docs.microsoft.com/en-us/azure/devops/repos/git/git-branching-guidance

**Comment by ericmtsai** [comment]
Thanks @wstlabs for the thorough writeup. This has been top-of-(my)-mind for awhile. Here are some of my thoughts back to you; these don't necessarily address every single one of your points but hopefully allow you to understand why we're doing things the way that we are.
- We considered our v1.0.0 release to be what we gave to the team that's developing the front end. Essentially this was the minimum required to set up the front end interface with both the data loading portion as well as the data analysis portion.
- The main reason for not tracking versioning as closely as you are suggesting is simply a lack of bandwidth and the short timeline to the election. The top priorities are, of course, working code and getting states' datafiles parsed/prepped/loaded, and then providing some reasonable amount of documentation that would allow a user to get started.
- We do leverage other branches besides `main`; we call these feature branches, and as the name suggests, we use them for larger scale feature development. The reason we haven't leveraged these for "normal" incremental development is that there is some overhead in managing these and we're trying to minimize the overhead.
- The changes that we are making and including into `main` _are_ incremental at this point. For example, as we accommodate a new state's data, we may see that there needs to be a tweak to code. My thinking is that this would typically be reflected in the "patch" number, and rather than releasing new versions/tags, this is essentially gets documented in the codebase by the jurisdiction and munger files that are included. This then becomes immediately available to end users as well instead of living in a branch that's more siloed, like a `develop` branch. Certainly when we introduce something that would affect the major or minor versions, we would be more aware of re-versioning/tagging as needed.

Anyways, no judgement on my end that what we've ended on is best (in fact, we know it's not best!) or even good, but only that it's sufficient at this point. But like I mentioned, I've been thinking about this for awhile, and your issue writeup is good impetus for me to get my thoughts in order. I'll add your great input to my thinking, and will bring these up to Stephanie along with some other development processes I've been considering. 

Thanks again!
